package com.pd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-06-06T19:15:00.118+05:30
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "DoubleItService", 
                  wsdlLocation = "file:/D:/workspace/mule/x509_client/src/main/wsdl/DoubleIt.wsdl",
                  targetNamespace = "http://www.example.org/contract/DoubleIt") 
public class DoubleItService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/contract/DoubleIt", "DoubleItService");
    public final static QName DoubleItPort = new QName("http://www.example.org/contract/DoubleIt", "DoubleItPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/workspace/mule/x509_client/src/main/wsdl/DoubleIt.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DoubleItService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/workspace/mule/x509_client/src/main/wsdl/DoubleIt.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DoubleItService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DoubleItService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DoubleItService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoubleItService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoubleItService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DoubleItService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DoubleItPortType
     */
    @WebEndpoint(name = "DoubleItPort")
    public DoubleItPortType getDoubleItPort() {
        return super.getPort(DoubleItPort, DoubleItPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DoubleItPortType
     */
    @WebEndpoint(name = "DoubleItPort")
    public DoubleItPortType getDoubleItPort(WebServiceFeature... features) {
        return super.getPort(DoubleItPort, DoubleItPortType.class, features);
    }

}
